# Generated by Django 5.1.4 on 2024-12-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_app_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='pic',
            field=models.ImageField(default='app/default.png', upload_to='app/'),
        ),
    ]
